### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DmitryOb** [ultimatecombo/pixijs-template#1]
```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run start --scripts-prepend-node-path=auto

> pixi-template@1.0.0 start /home/dmitry/Загрузки/pixijs-template
> webpack-dev-server --host 127.0.0.1 --hot --config webpack.dev.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /home/dmitry/Загрузки/pixijs-template/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:747:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/dmitry/Загрузки/pixijs-template/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/dmitry/Загрузки/pixijs-template/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pixi-template@1.0.0 start: `webpack-dev-server --host 127.0.0.1 --hot --config webpack.dev.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pixi-template@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dmitry/.npm/_logs/2021-01-20T10_24_31_343Z-debug.log

Process finished with exit code 1

```

**Comment by Yoreni** [comment]
i get this too

**Comment by pirtwo** [comment]
template updated, this should fix the issue.
